# Generated by Django 2.0.6 on 2018-06-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180616_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='source_record_id',
        ),
    ]
