# Generated by Django 2.0.4 on 2018-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='need_verification',
            field=models.BooleanField(default=True),
        ),
    ]
