# Generated by Django 2.0.4 on 2018-04-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('source_record_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('label_confirmed', models.BooleanField(default=False)),
                ('need_verification', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('source', 'source_record_id')},
        ),
    ]
