# Generated by Django 2.0.4 on 2018-04-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180421_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='need_verification',
        ),
    ]
