# Generated by Django 2.0.4 on 2018-06-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_record_need_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entity_data', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.Record')),
            ],
        ),
    ]
