# Generated by Django 2.0.4 on 2018-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='record',
            name='prediction_confidence',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
