# Generated by Django 2.0.4 on 2018-06-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180603_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='prediction_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
