# Generated by Django 2.0.6 on 2018-06-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180603_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='prediction_confidence',
            new_name='_prediction_confidence',
        ),
    ]
