# Generated by Django 2.0.6 on 2018-06-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180604_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='raw',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
