# Generated by Django 2.0.6 on 2018-06-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_entity_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPredictionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='label_prediction_results',
            field=models.ManyToManyField(to='api.LabelPredictionResult'),
        ),
    ]
