# Generated by Django 2.0.6 on 2018-06-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180608_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='label_prediction_results',
        ),
        migrations.AddField(
            model_name='labelpredictionresult',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_prediction_results', to='api.Record'),
        ),
    ]
