# Generated by Django 2.0.6 on 2018-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_record_source_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
