# Generated by Django 2.0.6 on 2018-06-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelsPredicted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels_predicted', to='records.Record')),
            ],
        ),
        migrations.RemoveField(
            model_name='labelpredictionresult',
            name='record',
        ),
        migrations.DeleteModel(
            name='LabelPredictionResult',
        ),
    ]
