# Generated by Django 2.0.6 on 2018-06-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180616_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ext_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
