# Generated by Django 2.0.6 on 2018-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20180616_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='pos_end',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='pos_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='value',
            field=models.CharField(default='df', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='raw',
            field=models.CharField(max_length=200),
        ),
    ]
