# Generated by Django 2.0.6 on 2018-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20180616_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(related_name='_record_tags_+', to='records.Tag'),
        ),
    ]
