#!/bin/bash

BUILD_DIR=_build
SERVICE_NAME=logulife-app


#
# CREATE BUILD DIRECTORY
#
echo "Creating docker build directory"

rm -rf $BUILD_DIR \
	&& mkdir $BUILD_DIR

ls | grep -v "$BUILD_DIR" | grep -v build | \
while read line;
	do cp -r $line $BUILD_DIR/;
done

#
# COPYING LIB
#
cp -r ../lib $BUILD_DIR/
cp ../deploy/*.deploy.json $BUILD_DIR/

cd $BUILD_DIR


#
# DELETE PYC AND CACHE
#
echo "Delete cache files"

find . -name "*.pyc" | \
while read line;
	do rm -f $line;
done

find . -name "*pycache*" | \
while read line;
	do rm -rf $line;
done


#
# SET DEGUG = FALSE
#
echo "Set debug = False"

sed -i.bak "s/DEBUG = True/DEBUG = False/g" src/app/settings.py


#
# Fetch version
#

VERSION=$(grep VERSION src/app/settings.py | awk '{print $3}' | sed "s/'//g")

#
# BUILD DOCKER IMAGE
#
echo "Start building docker image"

docker build -t $SERVICE_NAME:$VERSION .


#
# TAKE OUT THE GARBAGE
#
echo "Cleaning..."

cd .. && rm -rf $BUILD_DIR
