# Generated by Django 2.0.6 on 2018-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_int', models.IntegerField()),
                ('amount_fract', models.IntegerField()),
                ('direction', models.SmallIntegerField(choices=[(0, 'income'), (1, 'expense')])),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('category_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
