# Generated by Django 2.0.6 on 2018-06-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_fract',
            new_name='amount_decimal',
        ),
    ]
