# Generated by Django 2.0.6 on 2018-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0002_auto_20180604_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='rub', max_length=10),
        ),
    ]
