# Generated by Django 2.0.6 on 2018-06-04 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180603_2346'),
        ('spender', '0003_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Record'),
            preserve_default=False,
        ),
    ]
