# Generated by Django 2.0.2 on 2018-02-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('api', '0002_auto_20180204_2031'), ('api', '0003_auto_20180204_2032')]

    dependencies = [
        ('api', '0001_initial_squashed_0005_auto_20180204_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('source', 'source_record_id')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('owner', 'user_id')},
        ),
    ]
