# Generated by Django 2.0.6 on 2018-06-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_int', models.IntegerField()),
                ('amount_decimal', models.IntegerField()),
                ('currency', models.CharField(default='rub', max_length=10)),
                ('direction', models.SmallIntegerField(choices=[(0, 'income'), (1, 'expense')])),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('category_confirmed', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='records.Record')),
            ],
        ),
    ]
