# Generated by Django 2.0.6 on 2018-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0006_auto_20180713_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='direction',
            field=models.SmallIntegerField(choices=[(0, 'income'), (1, 'expense')], default=1),
            preserve_default=False,
        ),
    ]
