# Generated by Django 2.0.6 on 2018-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0007_category_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
