# Generated by Django 2.0.6 on 2018-07-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0008_auto_20180719_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
