# Generated by Django 2.0.6 on 2018-07-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0009_exchangerate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['symbol'], name='spender_exc_symbol_be0691_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['date'], name='spender_exc_date_2831c0_idx'),
        ),
    ]
