# Generated by Django 2.0.6 on 2018-07-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0010_auto_20180724_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='_default_currency',
            field=models.CharField(default='rub', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='default_currency_amount_decimal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='default_currency_amount_int',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
