# Generated by Django 2.0.6 on 2018-07-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spender', '0011_auto_20180724_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='default_currency_amount_decimal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='default_currency_amount_int',
            field=models.IntegerField(null=True),
        ),
    ]
